import type { CartographicTheme } from "./types";

export const CARTOGRAPHIC_THEMES: CartographicTheme[] = [
  {
    id: "light",
    title: "Светлая",
    description: "Повседневная архитектурная картография и подготовка листов.",
    font: "Manrope, Arial, sans-serif",
    paperTexture: "none",
    colors: {
      canvas: "#F4F7F9",
      paper: "#FFFFFF",
      text: "#111827",
      mutedText: "#64748B",
      buildingFill: "#CBD5E1",
      buildingStroke: "#64748B",
      buildingHover: "#FDE68A",
      buildingSelected: "#229ED9",
      roadCasing: "#FFFFFF",
      roadMotorway: "#D97706",
      roadPrimary: "#F59E0B",
      roadSecondary: "#FBBF24",
      roadLocal: "#94A3B8",
      roadPedestrian: "#A3A3A3",
      vegetationFill: "#86CFA3",
      vegetationStroke: "#3F8F5F",
      waterFill: "#9DDDF6",
      waterStroke: "#229ED9",
      terrainFill: "#E5E7EB",
      boundaryStroke: "#475569",
      utility: "#229ED9",
      selection: "#229ED9",
      whiteModelBuilding: "#FFFFFF",
      whiteModelTerrain: "#E7EAEE",
      shadow: "#CBD5E1",
    },
  },
  {
    id: "dark",
    title: "Темная",
    description: "Профессиональная тема для длительной работы.",
    font: "Manrope, Arial, sans-serif",
    paperTexture: "none",
    colors: {
      canvas: "#111827",
      paper: "#172033",
      text: "#F8FAFC",
      mutedText: "#AAB4C3",
      buildingFill: "#475569",
      buildingStroke: "#94A3B8",
      buildingHover: "#F59E0B",
      buildingSelected: "#38BDF8",
      roadCasing: "#0B1120",
      roadMotorway: "#FB923C",
      roadPrimary: "#FBBF24",
      roadSecondary: "#FDE68A",
      roadLocal: "#94A3B8",
      roadPedestrian: "#64748B",
      vegetationFill: "#2F6B4F",
      vegetationStroke: "#86CFA3",
      waterFill: "#155E75",
      waterStroke: "#67E8F9",
      terrainFill: "#1F2937",
      boundaryStroke: "#CBD5E1",
      utility: "#38BDF8",
      selection: "#38BDF8",
      whiteModelBuilding: "#F8FAFC",
      whiteModelTerrain: "#E2E8F0",
      shadow: "#020617",
    },
  },
  {
    id: "blueprint",
    title: "Синька",
    description: "Архитектурный стиль чертежа с глубоким синим фоном.",
    font: "Manrope, Arial, sans-serif",
    paperTexture: "blueprint-grid",
    colors: {
      canvas: "#0B2A42",
      paper: "#0E3553",
      text: "#D9F3FF",
      mutedText: "#8AC7DE",
      buildingFill: "#DDF7FF",
      buildingStroke: "#8FE7FF",
      buildingHover: "#FFE7A3",
      buildingSelected: "#FFFFFF",
      roadCasing: "#0B2A42",
      roadMotorway: "#8FE7FF",
      roadPrimary: "#75D7F2",
      roadSecondary: "#4FBBD8",
      roadLocal: "#6BAAC1",
      roadPedestrian: "#9BC8D8",
      vegetationFill: "#2F756B",
      vegetationStroke: "#8FE7C2",
      waterFill: "#145F86",
      waterStroke: "#B8F2FF",
      terrainFill: "#123D5E",
      boundaryStroke: "#B8F2FF",
      utility: "#FFFFFF",
      selection: "#FFFFFF",
      whiteModelBuilding: "#FFFFFF",
      whiteModelTerrain: "#DCEAF0",
      shadow: "#061928",
    },
  },
  {
    id: "print",
    title: "Печать",
    description: "Нейтральная контрастная тема для печати.",
    font: "Manrope, Arial, sans-serif",
    paperTexture: "subtle-grid",
    colors: {
      canvas: "#FAFAF7",
      paper: "#FFFFFF",
      text: "#111111",
      mutedText: "#595959",
      buildingFill: "#D9D9D6",
      buildingStroke: "#4A4A48",
      buildingHover: "#E7D37F",
      buildingSelected: "#111111",
      roadCasing: "#FFFFFF",
      roadMotorway: "#555555",
      roadPrimary: "#676767",
      roadSecondary: "#888888",
      roadLocal: "#A6A6A6",
      roadPedestrian: "#B8B8B8",
      vegetationFill: "#D8E1D4",
      vegetationStroke: "#7A8A73",
      waterFill: "#D9EAF2",
      waterStroke: "#6B8EA0",
      terrainFill: "#EFEFEB",
      boundaryStroke: "#111111",
      utility: "#111111",
      selection: "#111111",
      whiteModelBuilding: "#FFFFFF",
      whiteModelTerrain: "#ECECEC",
      shadow: "#D1D1D1",
    },
  },
];
